# Generated by Django 4.0.6 on 2022-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecase',
            name='pulsetxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecase',
            name='pupilstxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecase',
            name='respiratorytxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecase',
            name='skintxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecase',
            name='statetxt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
