# Generated by Django 4.1 on 2022-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0002_ambulancecase_pulsetxt_ambulancecase_pupilstxt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecase',
            name='barkod',
            field=models.ImageField(blank=True, null=True, upload_to='barkod/'),
        ),
    ]
