# Generated by Django 4.1 on 2022-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0005_alter_ambulancecase_barkod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecase',
            name='barkod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
