# Generated by Django 4.1 on 2022-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0006_alter_ambulancecase_barkod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecase',
            name='barkod',
            field=models.FileField(blank=True, null=True, upload_to='templates/barkod'),
        ),
    ]
