# Generated by Django 4.1 on 2022-11-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0008_ambulancecase_atn_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callcenter',
            old_name='where_patient_first_dropped_out',
            new_name='where_patient_first_dropped',
        ),
    ]
