# Generated by Django 4.1 on 2022-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0009_rename_where_patient_first_dropped_out_callcenter_where_patient_first_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='explanation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='patient_tel_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
