# Generated by Django 4.1.4 on 2023-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_forms', '0012_alter_callcenter_alarm_clock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecase',
            name='work_accident',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
