# Generated by Django 4.1 on 2022-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalPatientBirthDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalProtocolNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalGender', models.CharField(blank=True, max_length=1000, null=True)),
                ('processing_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalHour', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalPatientUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalPatientAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalPatientTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalPatientSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('generalDoctorUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalDoctorSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('generalWitnessUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalWitnessSignature', models.CharField(blank=True, max_length=5000, null=True)),
                ('generalRepresentativeUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalRepresentativeAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalRepresentativetTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalRepresentativeSignature', models.CharField(blank=True, max_length=5000, null=True)),
                ('generalRepresentativeDoctorUsername', models.CharField(blank=True, max_length=10000, null=True)),
                ('generalRepresentativeDoctorSignature', models.CharField(blank=True, max_length=5000, null=True)),
                ('generalRepresentativeWitnessUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('generalRepresentativeWitnessSignature', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjectionInformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection1', models.CharField(blank=True, max_length=1000, null=True)),
                ('injectionDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('injectionHour', models.CharField(blank=True, max_length=1000, null=True)),
                ('patientUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('patientAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('patientTelNo', models.CharField(blank=True, max_length=1000, null=True)),
                ('employeeUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('patientSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KVKKConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvkkName', models.CharField(blank=True, max_length=1000, null=True)),
                ('myRelatives', models.CharField(blank=True, max_length=1000, null=True)),
                ('legalPerson', models.CharField(blank=True, max_length=1000, null=True)),
                ('kvkkPatientUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('kvkkPatientDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('kvkkPatientSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='minorConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minorDiagnosis', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorOther', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorAlternative', models.CharField(blank=True, max_length=1000, null=True)),
                ('processing_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorHour', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorPatientUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorPatientAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorPatientTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorPatientSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('minorDoctorUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorDoctorSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('minorlegalRepresentativeUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorlegalRepresentativeAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorlegalRepresentativeTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorlegalRepresentativeSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('minorinterpreterUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('minorinterpreterSignatureText', models.CharField(blank=True, max_length=5000, null=True)),
                ('minorinterpreterTel', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunctureConsnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctureDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureHour', models.CharField(blank=True, max_length=1000, null=True)),
                ('puncturePatientUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('puncturePatientAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('puncturePatientTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('puncturePatientSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureDoctorUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureDoctorSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureWitnessUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureWitnessSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeAdress', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativetTel', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeDoctorUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeDoctorSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeWitnessUsername', models.CharField(blank=True, max_length=1000, null=True)),
                ('punctureRepresentativeWitnessSignatureText', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
