# Generated by Django 4.1 on 2022-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PunctureConsnt',
            new_name='PunctureConsent',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='generalPatientUsername1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
