# Generated by Django 4.1 on 2022-12-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0002_rename_punctureconsnt_punctureconsent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='generalRepresentativeDoctorSignature',
            new_name='generalRepresentativeDoctorSignatureText',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='generalRepresentativeSignature',
            new_name='generalRepresentativeSignatureText',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='generalRepresentativeWitnessSignature',
            new_name='generalRepresentativeWitnessSignatureText',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='generalWitnessSignature',
            new_name='generalWitnessSignatureText',
        ),
    ]
