# Generated by Django 4.1 on 2022-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0004_generalinformation_generalapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectioninformed',
            name='employeeSignatureText',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
