# Generated by Django 4.1 on 2022-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0005_injectioninformed_employeesignaturetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='generalApprovalTxt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
