# Generated by Django 4.1 on 2022-12-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0006_generalinformation_generalapprovaltxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvkkconsent',
            old_name='declaration',
            new_name='declarationTxt',
        ),
        migrations.RenameField(
            model_name='kvkkconsent',
            old_name='expression',
            new_name='expressionTxt',
        ),
    ]
