# Generated by Django 4.1 on 2022-12-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0007_rename_declaration_kvkkconsent_declarationtxt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvkkconsent',
            old_name='declarationTxt',
            new_name='declaration',
        ),
        migrations.RenameField(
            model_name='kvkkconsent',
            old_name='expressionTxt',
            new_name='expression',
        ),
    ]
