# Generated by Django 4.1 on 2022-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0008_rename_declarationtxt_kvkkconsent_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorconsent',
            name='minorApprovalTxt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
