# Generated by Django 4.1 on 2022-12-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0009_minorconsent_minorapprovaltxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='punctureconsent',
            name='punctureApprovalTxt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
