# Generated by Django 4.1 on 2022-12-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0010_punctureconsent_punctureapprovaltxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punctureconsent',
            old_name='punctureRepresentativetTel',
            new_name='punctureRepresentativeTel',
        ),
    ]
