# Generated by Django 4.1 on 2022-12-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0011_rename_puncturerepresentativettel_punctureconsent_puncturerepresentativetel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='processing_time',
            new_name='generalprocessingTime',
        ),
    ]
