# Generated by Django 4.1.4 on 2022-12-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentForms', '0013_rename_generalrepresentativettel_generalinformation_generalrepresentativetel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='generalApproval',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalApprovalTxt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalDoctorSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalPatientSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalRepresentativeDoctorSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalRepresentativeSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalRepresentativeWitnessSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='generalWitnessSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='injectioninformed',
            name='employeeSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='injectioninformed',
            name='patientSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='kvkkconsent',
            name='declaration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kvkkconsent',
            name='expression',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kvkkconsent',
            name='kvkkPatientSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorApproval',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorApprovalTxt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorDoctorSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorPatientSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorinterpreterSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='minorconsent',
            name='minorlegalRepresentativeSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureApproval',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureApprovalTxt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureDoctorSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='puncturePatientSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureRepresentativeDoctorSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureRepresentativeSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureRepresentativeWitnessSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='punctureconsent',
            name='punctureWitnessSignatureText',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
