version: "3"

  #networks:
  # web:
  #     external: true
  # bridge:
  #   driver: bridge

services:
    # CaddyServer reverse proxy
    caddy:
        restart: always
        image: caddy:2-alpine
        ports:
            - "443:443"
        command: caddy reverse-proxy --from --to http://0.0.0.0:8000
        #volumes:
        #    - /local/path/to/Caddyfile:/path/inside/continer/to/Caddyfile
        #     networks:
        #   - web
        #   - bridge

    # Django web app
    django:
        restart: always
        build: .
        ports:
          - "80:8000"
        depends_on:
          - pgdb
        #environment:
        #    - url=https://api.backend.example.com
        #command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        #networks:
        #   - bridge
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
          - POSTGRES_DB=hbys_filyos
          - POSTGRES_USER=healmedy 
          - POSTGRES_PASSWORD=mhacare1  
        volumes: 
          - pg-data:/var/lib/postgresql/data/
volumes:
  pg-data: