version: "3"

  #networks:
  # web:
  #     external: true
  # bridge:
  #   driver: bridge

services:
    # CaddyServer reverse proxy
    caddy:
        restart: always
        image: caddy:2-alpine
        ports:
            - "443:443"
        command: caddy reverse-proxy --from --to http://0.0.0.0:8000
        #volumes:
        #    - /local/path/to/Caddyfile:/path/inside/continer/to/Caddyfile
        #     networks:
        #   - web
        #   - bridge

    # Django web app
    django:
        restart: always
        build: .
        ports:
          - "80:8000"
        depends_on:
          - pgdb
        #environment:
        #    - url=https://api.backend.example.com
        #command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        #networks:
        #   - bridge
    dbsqlite:
    image: sqlite:latest
    container_name: sqlite-container
    environment:
      - DB_FILE=/var/lib/sqlite/data/mydatabase.db
volumes:
  pg-data: