# Generated by Django 4.0.6 on 2022-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('hours', models.TimeField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası')),
                ('tcNo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='TC Numarası')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres/Köy')),
                ('kurum', models.CharField(blank=True, max_length=11, null=True, verbose_name='Kurum')),
                ('diagnosis', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tanı')),
                ('intervention', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müdahale ve İlaçlar')),
                ('conclusion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sonuç')),
                ('doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doktor')),
            ],
        ),
    ]
