# Generated by Django 4.1 on 2022-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_blood_pressure',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.Tansiyon'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_fire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.Ateş'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_measurement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.Ölçüm'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_pulse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.Nabız'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_respirations_min',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.Solunum/DK'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_one_spo2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1.SPO2'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_blood_pressure',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Tansiyon'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_fire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Ateş'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_measurement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Ölçüm'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_pulse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Nabız'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_respirations_min',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Solunum/DK'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_second_spo2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2.SPO2'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_blood_pressure',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Tansiyon'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_fire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Ateş'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_measurement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Ölçüm'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_pulse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Nabız'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_respirations_min',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Solunum/DK'),
        ),
        migrations.AddField(
            model_name='records',
            name='record_third_spo2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3.SPO2'),
        ),
    ]
