# Generated by Django 4.1 on 2022-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_delete_institution_records_record_one_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
