# Generated by Django 4.1 on 2022-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurum'),
        ),
    ]
