# Generated by Django 4.1 on 2022-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_medicationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='scale_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='medications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
