# Generated by Django 4.1 on 2022-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_records_scale_used_alter_records_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='adress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adres/Köy'),
        ),
        migrations.AlterField(
            model_name='records',
            name='conclusion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sonuç'),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='doctor',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Doktor'),
        ),
        migrations.AlterField(
            model_name='records',
            name='hours',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='intervention',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Müdahale'),
        ),
        migrations.AlterField(
            model_name='records',
            name='kurum',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='records',
            name='medications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_blood_pressure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.Tansiyon'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_fire',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.Ateş'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_measurement',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.Ölçüm'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_pulse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.Nabız'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_respirations_min',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.Solunum/DK'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_one_spo2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1.SPO2'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_blood_pressure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.Tansiyon'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_fire',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.Ateş'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_measurement',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.Ölçüm'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_pulse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.Nabız'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_respirations_min',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.Solunum/DK'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_second_spo2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2.SPO2'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_blood_pressure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.Tansiyon'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_fire',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.Ateş'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_measurement',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.Ölçüm'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_pulse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.Nabız'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_respirations_min',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.Solunum/DK'),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_third_spo2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='3.SPO2'),
        ),
        migrations.AlterField(
            model_name='records',
            name='scale_used',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='tel',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='records',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ad Soyad'),
        ),
    ]
