# Generated by Django 4.0.6 on 2022-09-08 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_records_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='hours',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
