# Generated by Django 4.1 on 2022-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_records_adress_alter_records_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='way_of_application',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
