# Generated by Django 4.0.6 on 2022-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_records_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
