# Generated by Django 4.1 on 2022-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_records_way_of_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayOfApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_of_application', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
