# Generated by Django 4.0.6 on 2022-09-08 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_records_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='hours',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 9, 8, 14, 15, 0, 256316), null=True),
        ),
    ]
