# Generated by Django 4.0.6 on 2022-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_records_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='medications',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlaçlar'),
        ),
        migrations.AlterField(
            model_name='records',
            name='intervention',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Müdahale'),
        ),
    ]
